[package]
name = "steamdeckrun"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tempfile = "3.8"
nix = {version = "0.27", features = ["sched", "process", "mount", "user"]}
